### ISSUE TITLE
Crashes as soon as world loads

### ISSUE THREAD

**Issue by JamesTM2070** [rhysdh540/create-unlimited#1]
THe game boots up but when i try join a world it loads the terrain and then crashes the game

**Comment by rhysdh540** [comment]
Log please

**Comment by JamesTM2070** [comment]
here is the latest log and the crash report, Thanks
[crash-2023-05-05_22.06.53-client.txt](https://github.com/rhysdh540/create-unlimited/files/11410106/crash-2023-05-05_22.06.53-client.txt)
[latest.log](https://github.com/rhysdh540/create-unlimited/files/11410107/latest.log)

**Comment by rhysdh540** [comment]
Unlimited is currently broken with Steam 'n' Rails, so remove one of them. I'll have a fix for this out ~~soon~~ sometime.

**Comment by rhysdh540** [comment]
SNR compat will be in the 0.5.1 version.
