### ISSUE TITLE
[Suggestion] Bogeys not connected in order should be removed

### ISSUE THREAD

**Issue by CookerSmile** [rhysdh540/create-unlimited#10]
### Describe the Suggestion

When carriages overlap "Bogeys are not connected in order" is thrown ex:
[carriage 1, 2, 3 bogeys ordered as        3  2  3 1  2  1]

**Comment by rhysdh540** [comment]
This is a good idea, and I’ve tried to do it before, but unfortunately Create is hard-coded to only accept and assemble carriages in order, so ping this would require a significant rewrite of the train assembly code. If I ever figure out a way to implement this, then I will, but for now I’m unsure of how to.
