### ISSUE TITLE
[Bug] Incompatibility with MemoryLeakFix on Fabric

### ISSUE THREAD

**Issue by Deemitry88** [rhysdh540/create-unlimited#11]
### Describe the Bug

Create Unlimited seems to be incompatible with MemoryLeakFix, since it works when I remove MemoryLeakFix

### Reproduction Steps

On a Server
1. Install Create Unlimited and MemoryLeakFix on Fabric
2. Start the server
3. Crash

### Expected Result

It should not crash

### Crash Report or Log

https://gist.githubusercontent.com/Deemitry88/f0f9f9648ee8d64b9e7e52172fcb899d/raw/a4468b78d5b9e7b21c64b1b1f5b0913bc424ca97/latest.log

### Operating System

Windows 11

### Mod Build

0.4.0.52

### Minecraft Version

1.19.2

### Modloader

Fabric

### Modloader Version

0.14.21

### Other Mods

alternate-current-mc1.19-1.5.0.jar
architectury-6.5.85-fabric.jar
c2me-fabric-mc1.19.2-0.2.0+alpha.9.9.jar
Chunky-1.3.38.jar
collective-1.19.2-6.57.jar
create-fabric-0.5.1-b-build.1089+mc1.19.2.jar
createunlimited-0.4.0.52+mc1.19.2.jar
enhancedblockentities-0.7.2+1.19.2.jar
fabric-api-0.76.0+1.19.2.jar
Fastload+1.18.2-1.20-3.4.0.jar
ferritecore-5.0.3-fabric.jar
ForgeConfigAPIPort-v4.2.11-1.19.2-Fabric.jar
gottagofast-1.0.2-1.19.2.jar
krypton-0.2.1.jar
lazydfu-0.1.3.jar
lithium-fabric-mc1.19.2-0.11.1.jar
memoryleakfix-fabric-1.17+-1.0.0.jar
modernfix-fabric-5.7.0+mc1.19.2.jar
PuzzlesLib-v4.4.0-1.19.2-Fabric.jar
servercore-1.3.3-1.19.2.jar
skin-restorer-1.2.1.jar
smoothboot-fabric-1.19-1.7.1.jar
starlight-1.1.1+fabric.ae22326.jar
Steam_Rails-1.4.3+fabric-mc1.19.2.jar
tcdcommons-2.8+1.19.2.jar
vivecraft-1.19.2-0.0.15-fabric.jar
vmp-fabric-mc1.19.2-0.2.0+beta.7.30-all.jar
vrapi-3.0.3-1.19.2-fabric.jar
worldedit-mod-7.2.12.jar

**Comment by rhysdh540** [comment]
Are you able to reproduce this with just create, unlimited, and MLF?

**Comment by Deemitry88** [comment]
well I have a really bad server so I don't even think it will be able to boot without all these optimisation mods, but I'll try

**Comment by Deemitry88** [comment]
it crashed
[latest.log](https://github.com/rhysdh540/create-unlimited/files/12421351/latest.log)

**Comment by rhysdh540** [comment]
Can you add the mods [MixinTrace](https://modrinth.com/mod/mixintrace) and [StackDeobfuscator](https://modrinth.com/mod/stackdeobf) and try one more time? i'm not sure what might be causing it.

**Comment by Deemitry88** [comment]
here you go
[latest.log](https://github.com/rhysdh540/create-unlimited/files/12463093/latest.log)

**Comment by rhysdh540** [comment]
(probably) fixed in 0.5.0
