### ISSUE TITLE
error with mods

### ISSUE THREAD

**Issue by MrRoomba69** [rhysdh540/create-unlimited#12]
removing create unlimited fixed it
[crash-2023-08-31_17.38.41-fml.txt](https://github.com/rhysdh540/create-unlimited/files/12490963/crash-2023-08-31_17.38.41-fml.txt)

**Comment by rhysdh540** [comment]
Please use the issue templates ~~that I put so much effort into making~~ that I have provided for you.

**Comment by rhysdh540** [comment]
wait a minute they dont actually exist, hold on

**Comment by rhysdh540** [comment]
they exist now. Please use.
