### ISSUE TITLE
Can't dowload artifacts

### ISSUE THREAD

**Issue by gamecube-github** [rhysdh540/create-unlimited#12]
I went to Actions tab, I clicked on automated build #68 with check, scrolled down, clicked on forge artifacts - NOTHING HAPPENS! IT'S JUST A TEXT!
(give me download link using google drive or dropbox to forge artifacts plz)

**Comment by rhysdh540** [comment]
1. https://github.com/rhysdh540/create-ntl
2. make sure you're logged in to github. It wont work if you're not.
