### ISSUE TITLE
[Bug] Extendo grip mixin crashes on startup

### ISSUE THREAD

**Issue by ThatPersonWhoIsDead** [rhysdh540/create-unlimited#13]
### Describe the Bug

when i use createunlimited-0.5.0-31mc1.19.2 
the create mod doesnt load
![IMG_6757](https://github.com/rhysdh540/create-unlimited/assets/143760295/6cc50344-6c2d-4267-a901-33764a14846e)

### Reproduction Steps

1.put  createunlimited-0.5.0-31mc1.19.2.jar in your mods older
2. add create-1.19.2-0.5.1.c in the mods folder also 
3. launch minecraft and see the error
...

### Expected Result

not have the error ig? 

### Screenshots and Videos

![IMG_6757](https://github.com/rhysdh540/create-unlimited/assets/143760295/23fc25f9-1850-40f9-8102-2a9be8db2516)

### Crash Report or Log

https://pastebin.com/ZsQHcsM6

### Operating System

Windows 10

### Mod Build

31

### Minecraft Version

1.19.2

### Modloader

Forge

### Modloader Version

43.2.21

### Other Mods

create: alloyed
 Create: alloyed guns 
Framework
Mrcrayfish’s gun mod

**Comment by rhysdh540** [comment]
Crash report please

**Comment by ThatPersonWhoIsDead** [comment]
i edited it to have it

**Comment by rhysdh540** [comment]
Seems like a versioning error. I’ll fix it soon.

**Comment by ThatPersonWhoIsDead** [comment]
ok thank you!

**Comment by rhysdh540** [comment]
fixed? (it doesn't do anything but the game plays)
