### ISSUE TITLE
gradlew results a lot of files - not knowing which one is the actual addon

### ISSUE THREAD

**Issue by michelle1574** [rhysdh540/create-unlimited#14]
### Describe the Bug

.

### Reproduction Steps

.

### Expected Result

.

### Screenshots and Videos

.

### Operating System

.

### Mod Build

.

### Minecraft Version

1.19.2

### Modloader

Fabric

### Modloader Version

.

### Other Mods

.

### Additional Context

.

**Comment by rhysdh540** [comment]
What?

**Comment by michelle1574** [comment]
I wanted to post a question, but there was no category, so that was my issue.
My question is: where can I find the jar files of the actual compiled mod.

**Comment by rhysdh540** [comment]
If you want them, they are uploaded by GitHub actions or in the discord server in [builds](https://discord.com/channels/1058148300278222978/1136143445220675594). If you are compiling it yourself, they are in `build/libs/merged`.

**Comment by michelle1574** [comment]
Thank you!

**Comment by wofo73** [comment]
i am sorry but can you please go ahed and send the discord server link?

**Comment by rhysdh540** [comment]
[here](https://discord.gg/GeGm3DRDWY)
