### ISSUE TITLE
[Bug] Crash with Steam 'n' Rails

### ISSUE THREAD

**Issue by MozarteanChaos** [rhysdh540/create-unlimited#15]
### Describe the Bug

When loading a world with Create, Create: Unlimited, and Create: Steam 'n' Rails, the game crashes reliably.

### Reproduction Steps

1. Install the aforementioned mods (Create, Unlimited, Steam 'n' Rails)
2. Attempt to load or generate a world
3. Game crashes

### Expected Result

I'd expect the game to load the world without crashing.

### Crash Report or Log

https://pastebin.com/WvBxu1C2 https://pastebin.com/qNbWSqfG

### Operating System

Windows 10

### Mod Build

0.4.0.52

### Minecraft Version

1.19.2

### Modloader

Forge

### Modloader Version

43.2.21

### Other Mods

Create
Create: Steam 'n' Rails
Not Enough Crashes

### Additional Context

Not Enough Crashes blames Create for the crash, but I have reason to believe that it's actually a conflict between Unlimited and SnR, as when either of them is removed, the game functions perfectly fine. I did also spot something in the crash report that _looks_ like SnR is trying to inject something into a Create file, but is being blocked by Unlimited doing something else with the file. Take that with a grain of salt, though, I don't have a lot of experience with reading these.

All that said, I'm honestly not entirely sure which dev team I'm meant to report this to. If this is an issue on SnR's end, I'll gladly go to their repository and tell them about it instead.

**Comment by rhysdh540** [comment]
It is. Either you can wait for 0.5 to come out (which is pretty much done except for a couple architectury bugs I need them to fix) or use one of the dev builds. The most recent one is broken, so I would try some of the older ones.

**Comment by rhysdh540** [comment]
It is. Either you can wait for 0.5 to come out (which is pretty much done except for a couple architectury bugs I need them to fix) or use one of the dev builds. The most recent one is broken, so I would try some of the older ones.

**Comment by rhysdh540** [comment]
For future reference, don’t use NEC as it makes crash reports more annoying to read as well.

**Comment by rhysdh540** [comment]
Fixed in 0.5.0
