### ISSUE TITLE
How do I use the .jar file in curseforge once downloaded

### ISSUE THREAD

**Issue by Mrbagelll** [rhysdh540/create-unlimited#16]
### Describe the Bug

Cant get ntl to work

### Reproduction Steps

1. Dont know how
2.
3.
...

### Expected Result

Ntl to work

### Crash Report or Log

I dont know

### Operating System

Windows 10

### Mod Build

build 1.20

### Minecraft Version

1.20.1

### Modloader

Forge

### Modloader Version

47.1.0

### Other Mods

Create 0.5.1

**Comment by ThatPersonWhoIsDead** [comment]
step 1: copy the .jar
step 2: right click on the mod playlist modlist? press open folder
step 3: click on the mods folder in the folder that curseforge opens
spep 4: paste the create unlimited .jar in the mods folder that you just opened 
(i might upload a video tutorial if you need)

**Comment by Mrbagelll** [comment]
Do I need to put all the .jars or just 1

**Comment by ThatPersonWhoIsDead** [comment]
just the one for 1.20.1 if you want me to screenshare it please add me ln discord my username is: jarjarbinxlool 
IMPORTANT NOTE I AM NOT THE MOD OWNER IM JUST A NORMAL PERSON TRYING TO HELP

**Comment by Mrbagelll** [comment]
All right thank you

**Comment by Mrbagelll** [comment]
Can you send me a screenshot of what your mods folder looks like on discord?

**Comment by Mrbagelll** [comment]
My name is Mrbagek
