### ISSUE TITLE
OP kicks players[Bug] Forge 1.20.1 Server

### ISSUE THREAD

**Issue by wabbitking1234** [rhysdh540/create-unlimited#18]
### Describe the Bug

If I install this mod onto my server, it kicks anyone and everyone who is OPed out. Deleted my down all my mods one by one to find this as the issue

### Reproduction Steps

1. Create a Forge 1.20.1 Server
2. Add Create Unlimited mod to server and client
3. Join server
4. OP yourself with the server terminal
5. Get kicked

### Expected Result

Kicked from the game, back on server list. Cannot rejoin unless unOPed.
![Screenshot 2024-01-13 183852](https://github.com/rhysdh540/create-unlimited/assets/156489663/04becad2-c382-428f-88eb-7e982248efbc)

### Log

https://gist.github.com/wabbitking1234/4be188752f3220171a049761b872240a

### Operating System

Windows 11

### Mod Build

0.5.0

### Minecraft Version

1.20.1

### Modloader

Forge

### Modloader Version

47.2.0

### Other Mods

Just this one

**Comment by rhysdh540** [comment]
Trying to fix this, but due to Minecraft not wanting to give me the actual error, it's a little difficult. Just know that it's being worked on.

**Comment by wabbitking1234** [comment]
Thanks for the knowledge! I really loved this mod on my singleplayer worlds, and Absolutely liked that you ported NTL into 1.20.1. It would be nice if you could notify me somehow if you fix it. 

Also, kinda unrelated though, it is godly fun when you mix this with Create Interactive's train derailment. Weeeee goes the player as he gets cannon fired off to who knows where beyond the build limit due to incredibly cursed train rail placement.

**Comment by rhysdh540** [comment]
new lukewarm-fix is out on curse and modrinth.
