### ISSUE TITLE
Server crashes upon world load (different to #1)

### ISSUE THREAD

**Issue by TimDev9492** [rhysdh540/create-unlimited#2]
I added this addon to my mods and as soon as the world loads, the server crashes. This is, as far as I can tell, a different error than #1.
I'm quite certain, that Create Unlimited causes the issue, because the world loads fine without the mod. The error started occurring after adding this mod.

Crash report:
[crash-2023-05-08_16.07.14-server.txt](https://github.com/rhysdh540/create-unlimited/files/11421859/crash-2023-05-08_16.07.14-server.txt)
Log:
[latest.log](https://github.com/rhysdh540/create-unlimited/files/11421864/latest.log)

**Comment by rhysdh540** [comment]
closing this as #11 is more recent
