### ISSUE TITLE
[Suggestion] Add max signal placement distance

### ISSUE THREAD

**Issue by pernydev** [rhysdh540/create-unlimited#20]
### Describe the Suggestion

I love the features and idea of this mod! I would just love it even more if I could place my signal blocks farther away from my signal point on the track. This is useful for overhead signal bars. I don't want to deal with Display Links. And while you're on it, might as well disable all track point block limits.

### Screenshots and Videos

![image](https://github.com/rhysdh540/create-unlimited/assets/83672513/419ddd45-5df8-45c0-9d7f-762c7801ca0a)

### Additional Context

*ty <3*

**Comment by rhysdh540** [comment]
Doesn't seem too difficult, just need to make sure this doesn't break anything and then I'll add it. Thanks for the suggestion!

**Comment by rhysdh540** [comment]
@pernydev Will be released whenever fabric 0.5.1.f comes out.
