### ISSUE TITLE
[Bug] Off rail

### ISSUE THREAD

**Issue by JustablockCode** [rhysdh540/create-unlimited#28]
### Describe the Bug

I made track with monorail tracks from steam 'n' rails but then train keeps sending messages and stops "train has gone off track".

### Reproduction Steps

1. Download create unlimited 0.6.3 for 1.20.1, download steam 'n' rails 1.6.7 for 1.20.1, download Minecraft forge 1.20.1, download create 0.5.1.j for 1.20.1.
2. Make a singleplayer world.
3. Build a monorail track with big curves or drops(using create unlimited).
4. Make a monorail(train)
5. Assemble and drive around
...

### Expected Result

I expected it to just ride through

### Log

Nothing in logs

### Operating System

Windows 11 Home 

### Mod Build

0.6.3

### Minecraft Version

1.20.1

### Modloader

Forge

### Modloader Version

47.3.11

### Other Mods

Sodium, many optimization mods, eureka ships for valkryien skies, valkryien skies, addons for create like steam 'n' rails.

**Comment by rhysdh540** [comment]
Try changing the `extendedDriving` config value. See the [wiki](https://github.com/rhysdh540/create-unlimited/wiki#extendeddriving) for more information.

**Comment by JustablockCode** [comment]
thx

**Comment by JustablockCode** [comment]
ill try rq

**Comment by JustablockCode** [comment]
still after setting it to 0.001 it was still saying that went offrail on some sharp upclimbs

**Comment by rhysdh540** [comment]
Can you share a video of what you're doing to make this happening?

**Comment by JustablockCode** [comment]
umm i can only tomorrow

**Comment by rhysdh540** [comment]
That's alright, whenever you have the time. If you have a discord account you can also join our server, I might respond a little faster there.

**Comment by JustablockCode** [comment]
> That's alright, whenever you have the time. If you have a discord account you can also join our server, I might respond a little faster there.

ok then we will continue the talk on discord
