### ISSUE TITLE
1.19.2 latest create fabric is incompatable [dependency]

### ISSUE THREAD

**Issue by netcore10** [rhysdh540/create-unlimited#5]
i think dependencies need updating
![image](https://github.com/rhysdh540/create-unlimited/assets/181536/b8bd75e7-1432-46cc-8878-a257bb70c3a6)

**Comment by rhysdh540** [comment]
Good catch! Updated [here](https://modrinth.com/mod/create-unlimited/version/Ib6YONZh)
