### ISSUE TITLE
Mod needs a dependency update again [Bug] 

### ISSUE THREAD

**Issue by netcore10** [rhysdh540/create-unlimited#8]
### Describe the Bug

Dependency error

### Reproduction Steps

1.add create
2.add create unlimited
3. fail.
...

### Expected Result

to launch

### Screenshots and Videos

![image](https://github.com/rhysdh540/create-unlimited/assets/181536/39f887f2-be2c-4e35-b6ce-f2c86d3804a6)

### Operating System

windows 10

### Mod Build

0.3.1

### Minecraft Version

1.19.2

### Modloader

Fabric

### Modloader Version

0.14.21

**Comment by rhysdh540** [comment]
thanks!
