### ISSUE TITLE
Add compatibility for Create Steam and Rails

### ISSUE THREAD

**Issue by themanofpolybridge2** [rhysdh540/create-unlimited#9]
### Describe the Suggestion

as in the title i want compactibility for create steam and rails

**Comment by rhysdh540** [comment]
Should be 100% compatible with steam n’ rails. I use both with create 1.19.2 0.5.1.b. Maybe you’re trying to use SNR on patch c?

**Comment by TheBastosBob** [comment]
in fact the latest version work great with steam and rails for me but the version 0.3.1 i tested with 0.5.0i doen't work

**Comment by rhysdh540** [comment]
Yeah it doesn’t. Don’t plan on making them compatible on an old version of create.
